export const FETCH_CONTRACTS = 'FETCH_CONTRACTS';
export const SEARCH_CONTRACTS = 'SEARCH_CONTRACTS';

export const ADD_CONTRACT = 'ADD_CONTRACT';
export const DELETE_CONTRACT = 'DELETE_CONTRACT';
export const EDIT_CONTRACT = 'EDIT_CONTRACT';
